### ISSUE TITLE
I am not able to cpu-features using npm command 

### ISSUE THREAD

**Issue by tnavanath** [mscdex/cpu-features#11]
I am not able to cpu-features using npm command 

Received error :
throw new error unable to detect compiler type.
Please suggest solution

I was trying to execute the module at windows and Linus machine I got the same error.
Also I don't see it has good compatibility with windows machine.

**Comment by mscdex** [comment]
Do you have a working build environment installed that is supported by [node-gyp](https://github.com/nodejs/node-gyp/blob/main/README.md)?

**Comment by mjsornp** [comment]
I had the same problem。

throw new Error('Unable to detect compiler type');
