### ISSUE TITLE
An error occurred when I used rollup packaging

### ISSUE THREAD

**Issue by backgron** [mscdex/cpu-features#12]
![image](https://user-images.githubusercontent.com/81201582/203560243-29e46161-f2c8-4963-ae49-53340a4a9ac7.png)
![image](https://user-images.githubusercontent.com/81201582/203560386-87b345ab-4637-4ea7-8184-6e4f1c4db8f1.png)
Could it be a node-ssh dependency issue？
Could it be a node-ssh dependency issue？

**Comment by mscdex** [comment]
I can't help you there, I've never used rollup.
