### ISSUE TITLE
No Support for Apple M1 Pro in 0.0.4

### ISSUE THREAD

**Issue by aaronmassicotte** [mscdex/cpu-features#13]
cpu-features.js
```
const features = require('cpu-features')();
console.log(features)
```

node cpu-features.js
`{ arch: 'unknown', flags: {} }`

sysctl -n machdep.cpu.brand_string
`Apple M1 Pro`

**Comment by Brooooooklyn** [comment]
Try this package: https://github.com/Brooooooklyn/sysinfo

**Comment by aaronmassicotte** [comment]
I've applied the patch and this is the output:

```
{
  arch: 'aarch64',
  implementer: 16777228,
  variant: 2,
  part: 458787763,
  revision: 4,
  flags: {
    fp: true,
    asimd: true,
    aes: true,
    pmull: true,
    sha1: true,
    crc32: true,
    atomics: true,
    fphp: true,
    jscvt: true,
    fcma: true,
    lrcpc: true,
    sha3: true,
    sha512: true,
    asimdfhm: true,
    ssbs: true,
    sb: true
  }
}
```

I am used to seeing `arm64` as the name, but otherwise LGTM

**Comment by mscdex** [comment]
Thanks for the feedback, I've added and applied the unofficial patch for now. I'm still hoping upstream will merge it at some point, but until then ...
