### ISSUE TITLE
I am unable to install cpu-features using the npm install command.

### ISSUE THREAD

**Issue by adventurer-ik** [mscdex/cpu-features#14]
I am unable to install cpu-features using the npm install command.

Received error :
```
make: *** [Release/obj.target/cpu_features/deps/cpu_features/src/impl_x86_linux_or_android.o] Error 1
make: Leaving directory `/home/root/ik/node_modules/cpu-features/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 3.10.0-693.el7.x86_64
gyp ERR! command "/usr/local/nvm/versions/node/v12.16.1/bin/node" "/usr/local/nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/root/ik/node_modules/cpu-features
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
```

When installing the ssh2-sftp-client or ssh2 modules, I encounter an error while installing cpu-features.

my env :
centos7.4
gcc 4.8.5
python 2.7.5 or python3.8 (The error occurs with both Python 2.7.5 and Python 3.8.)
node v12.16.1.

Please suggest solution.

**Comment by mscdex** [comment]
Two suggestions:

1. The actual error is either above these lines or in the npm installation log file on disk and would be more helpful. If I had to take a wild guess though, maybe you don't have build tools installed?

2. `cpu-features` is an *optional dependency* of `ssh2`, so it's not required to use it.

**Comment by adventurer-ik** [comment]
When running 'npm install ssh2-sftp-client,' I encounter the following log. Is there anything I can do from here?

npm debug.log:
[root@rms-dev test]# npm install ssh2-sftp-client@8.1.0

> cpu-features@0.0.8 install /home/root/ik/test/node_modules/cpu-features
> node buildcheck.js > buildcheck.gypi && node-gyp rebuild

make: Entering directory `/home/root/ik/test/node_modules/cpu-features/build'
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/impl_aarch64_linux_or_android.o
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/impl_arm_linux_or_android.o
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/impl_mips_linux_or_android.o
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/impl_ppc_linux.o
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/impl_x86_freebsd.o
  CC(target) Release/obj.target/cpu_features/deps/cpu_features/src/impl_x86_linux_or_android.o
In file included from ../deps/cpu_features/src/impl_x86__base_implementation.inl:89:0,
                 from ../deps/cpu_features/src/impl_x86_linux_or_android.c:20:
../deps/cpu_features/src/copy.inl: In function ‘copy’:
../deps/cpu_features/src/copy.inl:18:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (size_t i = 0; i < count; ++i) dst[i] = src[i];
   ^
../deps/cpu_features/src/copy.inl:18:3: note: use option -std=c99 or -std=gnu99 to compile your code
In file included from ../deps/cpu_features/src/impl_x86__base_implementation.inl:91:0,
                 from ../deps/cpu_features/src/impl_x86_linux_or_android.c:20:
../deps/cpu_features/src/equals.inl: In function ‘equals’:
../deps/cpu_features/src/equals.inl:19:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (size_t i = 0; i < count; ++i)
   ^
In file included from ../deps/cpu_features/src/impl_x86_linux_or_android.c:20:0:
../deps/cpu_features/src/impl_x86__base_implementation.inl: In function ‘ParseLeaf2’:
../deps/cpu_features/src/impl_x86__base_implementation.inl:1730:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (size_t i = 0; i < sizeof(data); ++i) {
   ^
../deps/cpu_features/src/impl_x86__base_implementation.inl: In function ‘ParseCacheInfo’:
../deps/cpu_features/src/impl_x86__base_implementation.inl:1746:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int index = 0; info.size < CPU_FEATURES_MAX_CACHE_LEVEL; ++index) {
   ^
../deps/cpu_features/src/impl_x86__base_implementation.inl: In function ‘ParseCacheInfoLegacyAMD’:
../deps/cpu_features/src/impl_x86__base_implementation.inl:1873:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < LEGACY_AMD_MAX_CACHE_LEVEL; ++i) {
   ^
../deps/cpu_features/src/impl_x86_linux_or_android.c: In function ‘DetectFeaturesFromOs’:
../deps/cpu_features/src/impl_x86_linux_or_android.c:37:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (bool stop = false; !stop;) {
     ^
make: *** [Release/obj.target/cpu_features/deps/cpu_features/src/impl_x86_linux_or_android.o] Error 1
make: Leaving directory `/home/root/ik/test/node_modules/cpu-features/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 3.10.0-693.el7.x86_64
gyp ERR! command "/usr/local/nvm/versions/node/v12.16.1/bin/node" "/usr/local/nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/root/ik/test/node_modules/cpu-features
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok

> ssh2@1.14.0 install /home/root/ik/test/node_modules/ssh2
> node install.js

make: Entering directory `/home/root/ik/test/node_modules/ssh2/lib/protocol/crypto/build'
  CXX(target) Release/obj.target/sshcrypto/src/binding.o
  SOLINK_MODULE(target) Release/obj.target/sshcrypto.node
  COPY Release/sshcrypto.node
make: Leaving directory `/home/root/ik/test/node_modules/ssh2/lib/protocol/crypto/build'
Succeeded in building optional crypto binding
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cpu-features@0.0.8 (node_modules/cpu-features):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cpu-features@0.0.8 install: `node buildcheck.js > buildcheck.gypi && node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ ssh2-sftp-client@8.1.0
added 18 packages from 23 contributors in 3.95s

**Comment by mscdex** [comment]
It looks like your compiler defaults to some other C standard, presumably older. What does `gcc -v` show?

I can look at explicitly setting `std` for the cpu_features dependency.

Even without any additional changes, as noted by the last few lines of the output, you can already use your installed package (`ssh2-sftp-client`).

**Comment by adventurer-ik** [comment]
Thank you for continuing to provide answers.

gcc -v is as follows:
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) 


Although I managed to install it in the development environment somehow, I am trying to fix the issue that arises during the package build process.
The problem lies in the error that occurs during the npm i stage, causing the process to terminate.

**Comment by mscdex** [comment]
> gcc version 4.8.5 20150623

Ah yep, that's quite old and would explain things. gcc pre-4.9.4 defaults to gnu89/gnu90.

> The problem lies in the error that occurs during the npm i stage, causing the process to terminate.

Are you referring to a different issue or ? Everything compilable for this module is completely optional and should not result in abrupt termination of the installation process.
