### ISSUE TITLE
Error from checkbuilder.js deps

### ISSUE THREAD

**Issue by ltb27** [mscdex/cpu-features#15]
I got this error when install cpu-feature in Window 11 and nodejs 16.8.0 

D:\\Nobi\\Ecomsea\\node_modules\\buildcheck\\lib\\index.js:133
        throw new Error('Unable to detect compiler type');
        ^

Error: Unable to detect compiler type

i dont know why

**Comment by mscdex** [comment]
Do you have build tools installed? If not, that'd be why.

You can install build tools either by installing MSVC or by selecting the [native tools option when running the Node.js MSI installer](https://courses.cs.washington.edu/courses/cse154/19au/resources/assets/node/windows/img/nodeInstallNative.png).

**Comment by justsaman2712** [comment]
ok, let me check it . thank u so much
