### ISSUE TITLE
undefined symbol: node_module_register

### ISSUE THREAD

**Issue by 1bye** [mscdex/cpu-features#19]
Hi there!

I've been using `dockerode` in my project for a month without any issues, but yesterday an error occurred for no apparent reason. The error message is as follows:

```
bun: symbol lookup error: /home/mrbye/Documents/GitHub/flow-server/node_modules/cpu-features/build/Release/cpufeatures.node: undefined symbol: node_module_register
```

Here are the specifications for my environment:

- Ubuntu 22
- Node.js 20
- Bun 1.0.21
- Gcc 11.4.0

When I run `npm ls`, I get the following output:

```
flow-server@1.0.50 /home/mrbye/Documents/GitHub/flow-server
└─┬ dockerode@4.0.2
  └─┬ docker-modem@5.0.3
    └─┬ ssh2@1.15.0
      └── cpu-features@0.0.9
```

I'm using `bun` in my project, but I also tried building the package using `node`. Also tried to build project into docker, but the same error. Do you have any ideas on how to resolve this issue?

(I don't updated bun, and used it while month)

Thanks!

**Comment by mscdex** [comment]
This project only supports node, not bun, as they are two very different runtimes.

If `npm ls` shows `cpu-features`, then it was installed correctly.

**Comment by 1bye** [comment]
Hmm, but I've used your package while a months... And everything was good. I will try do issue in bun, thanks

**Comment by 1bye** [comment]
Idk but, I downgraded bun into `1.0.15` and everything is works, thanks
Closing issue
