### ISSUE TITLE
GitHub releases tab missing latest release v0.0.9

### ISSUE THREAD

**Issue by MikeMcC399** [mscdex/cpu-features#20]
The GitHub releases tab https://github.com/mscdex/cpu-features/releases shows only release [v0.0.2](https://github.com/mscdex/cpu-features/releases/tag/v0.0.2) and this release is shown as `Latest`.

This is not aligned to the latest release published to npm which is `0.0.9`, not `0.0.2`.

```text
$ npm view cpu-features dist-tags
{ latest: '0.0.9' }
```

The intermediate releases `'0.0.3', '0.0.4', '0.0.5', '0.0.6', '0.0.7', '0.0.8'` are also missing from the GitHub releases tab:

```text
$ npm view cpu-features versions
[
  '0.0.1', '0.0.2',
  '0.0.3', '0.0.4',
  '0.0.5', '0.0.6',
  '0.0.7', '0.0.8',
  '0.0.9'
]
```

See also https://www.npmjs.com/package/cpu-features?activeTab=versions

![image](https://github.com/mscdex/cpu-features/assets/66998419/2bdc4d76-b493-485c-bc59-0fbff50d5768)

## Suggestion

It would be very helpful to have the missing releases `'0.0.3', '0.0.4', '0.0.5', '0.0.6', '0.0.7', '0.0.8', '0.0.9'` added to the [GitHub releases tab](https://github.com/mscdex/cpu-features/releases) and for `'0.0.9'` to be marked as `Latest` there.

**Comment by mscdex** [comment]
The Github releases were part of an experiment to provide pre-compiled versions of the addon. That experiment is no longer.

**Comment by MikeMcC399** [comment]
@mscdex 

Thanks for your response and explanation!

I would still encourage you to create a new GitHub release `v0.0.9` and mark that as `latest` corresponding to the latest release on npm even if pre-compiled versions are no longer being created. In my experience it is a simple action to create a release manually and it is not necessary to have files associated with a release. Only a tag is necessary.

I can't point to any hard and fast rules on this or even a best practice document, however many other npm modules sourced from GitHub do it this way. It has the advantage that the GitHub release tab shows the latest release at a glance. I was personally misled by the release tab showing `v0.0.2` as `latest` and it would have helped me as a newcomer to the repo if it had shown `v0.0.9` as `latest`.

**Comment by MikeMcC399** [comment]
@mscdex 

Since the releases aren't being used anymore, you might want to consider removing the display from the home page. Click on the setting gear-wheel next to About on https://github.com/mscdex/cpu-features to access the UI which allows deselection of "Releases".

This is a screenshot from a fork, just to illustrate the UI:

![image](https://github.com/user-attachments/assets/9d9f6eac-b94f-4004-bbe6-7e2ed96be00b)
